# train.py
"""
MerchAI — Real ML Training Pipeline (v5/v6 shared — no changes needed)
Trains 4 ML models on the retail dataset and saves them to models/

MODELS TRAINED:
  Model 1: Demand Forecasting     — GradientBoostingRegressor
           Predicts next-7-day demand from sales history + context
  Model 2: Markdown Classifier    — GradientBoostingClassifier
           Predicts discount tier: 0=None 1=Light 2=Moderate 3=Aggressive
  Model 3: Health Score Regressor — GradientBoostingRegressor
           Predicts inventory health score 0-100
  Model 4: Price Elasticity Model — Linear models per category
           Predicts demand uplift % from a price change %

RUN:  python3 train.py
PREREQ: data/retail_dataset.csv  (generated by generate_dataset.py)
"""

import pandas as pd
import numpy as np
import joblib, os, json, time
from sklearn.ensemble import GradientBoostingRegressor, GradientBoostingClassifier
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import (mean_absolute_error, mean_squared_error, r2_score,
                              accuracy_score, classification_report, f1_score)
from sklearn.pipeline import Pipeline
from datetime import datetime

np.random.seed(42)
os.makedirs("models", exist_ok=True)

print("=" * 65)
print("  MerchAI — Real ML Training Pipeline")
print("=" * 65)

# ── Load Dataset ─────────────────────────────────────────────
print("\n[1/5] Loading dataset...")
df = pd.read_csv("data/retail_dataset.csv")
print(f"  Records: {len(df):,} | Features: {len(df.columns)}")

# ── Feature Engineering ──────────────────────────────────────
print("\n[2/5] Engineering features...")

df["v_week"]         = df["sales_last_week"]  / 7.0
df["v_month"]        = df["sales_last_month"] / 30.0
df["momentum"]       = df["v_week"] / df["v_month"].clip(lower=0.01)
df["momentum"]       = df["momentum"].clip(0.2, 4.0)
df["blended_vel"]    = df["v_week"] * 0.6 + df["v_month"] * 0.4
df["adj_velocity"]   = df["blended_vel"] * df["season_factor"]

df["sdr"]            = df["stock"] / (df["adj_velocity"] * 7.0).clip(lower=0.01)
df["sdr"]            = df["sdr"].clip(0, 50)
df["days_excess"]    = (df["days_to_sell"] - df["expiry_days"]).clip(lower=0)
df["cover_vs_lt"]    = df["days_to_sell"] / df["lead_time"].clip(lower=1)

df["price_vs_comp"]  = df["price_ratio"] - 1.0
df["disc_potential"] = (1 - df["cost_price"] / df["base_price"].clip(lower=1)) * 100

df["demand_pressure"] = df["actual_demand_7d"] / df["stock"].clip(lower=1) * 7
df["log_stock"]       = np.log1p(df["stock"])
df["log_demand"]      = np.log1p(df["actual_demand_7d"])

print(f"  Engineered {len(df.columns)} total columns")

# ════════════════════════════════════════════════════════════
# MODEL 1: DEMAND FORECAST (GBR)
# ════════════════════════════════════════════════════════════
print("\n[3/5] Training Model 1: Demand Forecast (GradientBoosting)...")

DEMAND_FEATURES = [
    "v_week", "v_month", "blended_vel", "adj_velocity", "momentum",
    "season_factor", "festival_factor", "category_enc",
    "month", "week_of_year", "is_festival", "is_weekend",
    "price_ratio", "margin_pct", "lead_time",
    "demand_cv", "log_stock", "sdr",
]

X_d = df[DEMAND_FEATURES].fillna(0)
y_d = df["actual_demand_7d"]

X_train_d, X_test_d, y_train_d, y_test_d = train_test_split(
    X_d, y_d, test_size=0.15, random_state=42
)

demand_model = GradientBoostingRegressor(
    n_estimators=400, learning_rate=0.06, max_depth=5,
    min_samples_leaf=12, subsample=0.80, max_features="sqrt",
    random_state=42, validation_fraction=0.10, n_iter_no_change=25,
)

t0 = time.time()
demand_model.fit(X_train_d, y_train_d)
t1 = time.time()

pred_d  = np.maximum(demand_model.predict(X_test_d), 0)
mae_d   = mean_absolute_error(y_test_d, pred_d)
rmse_d  = np.sqrt(mean_squared_error(y_test_d, pred_d))
r2_d    = r2_score(y_test_d, pred_d)
mape_d  = np.mean(np.abs((y_test_d - pred_d) / y_test_d.clip(lower=1))) * 100

print(f"  MAE  = {mae_d:.2f} units  |  RMSE = {rmse_d:.2f}")
print(f"  R²   = {r2_d:.4f}          |  MAPE = {mape_d:.1f}%")
print(f"  Time = {t1-t0:.1f}s")

feat_imp = dict(zip(DEMAND_FEATURES, demand_model.feature_importances_.round(4)))
top5 = sorted(feat_imp.items(), key=lambda x: x[1], reverse=True)[:5]
print(f"  Top features: {[f'{k}={v:.3f}' for k,v in top5]}")

joblib.dump(demand_model,    "models/demand_model.pkl")
joblib.dump(DEMAND_FEATURES, "models/demand_features.pkl")
print("  Saved → models/demand_model.pkl")

# ════════════════════════════════════════════════════════════
# MODEL 2: MARKDOWN CLASSIFIER (GBC)
# ════════════════════════════════════════════════════════════
print("\n[3/5] Training Model 2: Markdown Decision Classifier...")

MARKDOWN_FEATURES = [
    "days_to_sell", "expiry_days", "days_excess", "fraction_at_risk",
    "will_sell_before_expiry", "sdr", "stock_weeks",
    "adj_velocity", "momentum",
    "category_enc", "margin_pct", "disc_potential",
    "price_ratio", "festival_factor", "season_factor",
]

X_m = df[MARKDOWN_FEATURES].fillna(0)
y_m = df["discount_tier"]

X_train_m, X_test_m, y_train_m, y_test_m = train_test_split(
    X_m, y_m, test_size=0.15, random_state=42, stratify=y_m
)

markdown_model = GradientBoostingClassifier(
    n_estimators=350, learning_rate=0.08, max_depth=4,
    min_samples_leaf=15, subsample=0.80, max_features="sqrt",
    random_state=42,
)

t0 = time.time()
markdown_model.fit(X_train_m, y_train_m)
t1 = time.time()

pred_m = markdown_model.predict(X_test_m)
acc_m  = accuracy_score(y_test_m, pred_m)
f1_m   = f1_score(y_test_m, pred_m, average="weighted")

print(f"  Accuracy = {acc_m*100:.1f}%  |  Weighted F1 = {f1_m:.4f}")
print(f"  Time = {t1-t0:.1f}s")
print("  Per-class report:")
report_lines = classification_report(
    y_test_m, pred_m,
    target_names=["No Discount","Light","Moderate","Aggressive"],
    zero_division=0).split("\n")
for line in report_lines[2:6]:
    if line.strip():
        print(f"    {line}")

joblib.dump(markdown_model,    "models/markdown_model.pkl")
joblib.dump(MARKDOWN_FEATURES, "models/markdown_features.pkl")
print("  Saved → models/markdown_model.pkl")

# ════════════════════════════════════════════════════════════
# MODEL 3: HEALTH SCORE REGRESSOR (GBR)
# ════════════════════════════════════════════════════════════
print("\n[4/5] Training Model 3: Inventory Health Score Regressor...")

HEALTH_FEATURES = [
    "sdr", "stock_weeks", "cover_vs_lt",
    "fraction_at_risk", "will_sell_before_expiry",
    "days_to_sell", "expiry_days", "days_excess",
    "adj_velocity", "momentum",
    "price_ratio", "margin_pct",
    "category_enc", "season_factor", "festival_factor",
    "demand_cv", "lead_time",
]

X_h = df[HEALTH_FEATURES].fillna(0)
y_h = df["health_score"].clip(0, 100)

X_train_h, X_test_h, y_train_h, y_test_h = train_test_split(
    X_h, y_h, test_size=0.15, random_state=42
)

health_model = GradientBoostingRegressor(
    n_estimators=350, learning_rate=0.07, max_depth=5,
    min_samples_leaf=10, subsample=0.80, max_features="sqrt",
    random_state=42, validation_fraction=0.10, n_iter_no_change=20,
)

t0 = time.time()
health_model.fit(X_train_h, y_train_h)
t1 = time.time()

pred_h = health_model.predict(X_test_h).clip(0, 100)
mae_h  = mean_absolute_error(y_test_h, pred_h)
rmse_h = np.sqrt(mean_squared_error(y_test_h, pred_h))
r2_h   = r2_score(y_test_h, pred_h)

print(f"  MAE  = {mae_h:.2f} pts  |  RMSE = {rmse_h:.2f}")
print(f"  R²   = {r2_h:.4f}")
print(f"  Time = {t1-t0:.1f}s")

joblib.dump(health_model,    "models/health_model.pkl")
joblib.dump(HEALTH_FEATURES, "models/health_features.pkl")
print("  Saved → models/health_model.pkl")

# ════════════════════════════════════════════════════════════
# MODEL 4: PRICE ELASTICITY (Ridge per Category)
# ════════════════════════════════════════════════════════════
print("\n[4/5] Training Model 4: Price Elasticity per Category...")

ELAST_FEATURES  = ["price_vs_comp", "season_factor", "festival_factor",
                   "stock_weeks", "margin_pct", "momentum"]
elasticity_models = {}

for cat in ["Fashion", "Grocery", "Electronics", "FMCG", "Seasonal"]:
    cat_df = df[df["category"] == cat].copy()
    if len(cat_df) < 200:
        continue

    base_demand  = cat_df["blended_vel"] * 7
    actual_d     = cat_df["actual_demand_7d"]
    demand_ratio = (actual_d / base_demand.clip(lower=0.01)).clip(0.1, 5.0)
    y_e          = np.log(demand_ratio)
    X_e          = cat_df[ELAST_FEATURES].fillna(0)

    pipeline = Pipeline([
        ("scaler", StandardScaler()),
        ("ridge",  Ridge(alpha=1.0)),
    ])
    pipeline.fit(X_e, y_e)

    cv_scores = cross_val_score(pipeline, X_e, y_e, cv=5, scoring="r2")
    print(f"  {cat}: R²_cv = {cv_scores.mean():.3f} ± {cv_scores.std():.3f}  (n={len(cat_df):,})")

    elasticity_models[cat] = pipeline

joblib.dump(elasticity_models, "models/elasticity_models.pkl")
joblib.dump(ELAST_FEATURES,    "models/elasticity_features.pkl")
print("  Saved → models/elasticity_models.pkl")

# ════════════════════════════════════════════════════════════
# SAVE METADATA
# ════════════════════════════════════════════════════════════
print("\n[5/5] Saving model metadata...")

metadata = {
    "trained_on":        datetime.now().strftime("%Y-%m-%d %H:%M"),
    "records":           len(df),
    "demand_model":      {"mae": round(mae_d,3), "rmse": round(rmse_d,3), "r2": round(r2_d,4), "mape_pct": round(mape_d,1)},
    "markdown_model":    {"accuracy": round(acc_m,4), "f1_weighted": round(f1_m,4)},
    "health_model":      {"mae": round(mae_h,3), "rmse": round(rmse_h,3), "r2": round(r2_h,4)},
    "categories":        ["Fashion", "Grocery", "Electronics", "FMCG", "Seasonal"],
    "demand_features":   DEMAND_FEATURES,
    "markdown_features": MARKDOWN_FEATURES,
    "health_features":   HEALTH_FEATURES,
    "elasticity_features": ELAST_FEATURES,
}

with open("models/metadata.json", "w") as f:
    json.dump(metadata, f, indent=2)
print("  Saved → models/metadata.json")

print("\n" + "=" * 65)
print("  TRAINING COMPLETE — 4 Models Ready")
print("=" * 65)
print(f"  Model 1 — Demand Forecast  : R² = {r2_d:.4f}, MAPE = {mape_d:.1f}%")
print(f"  Model 2 — Markdown Decider : Accuracy = {acc_m*100:.1f}%, F1 = {f1_m:.3f}")
print(f"  Model 3 — Health Score     : R² = {r2_h:.4f}, MAE  = {mae_h:.2f}")
print(f"  Model 4 — Price Elasticity : Per-category Ridge (5-fold CV)")
print("=" * 65)
print("\nRun:  python app.py  to start the server.")